// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REASite.Data;

#nullable disable

namespace REASite.Migrations
{
    [DbContext(typeof(REASiteDbContext))]
    [Migration("20250423115136_AddedSeedingsimpleDataApartment")]
    partial class AddedSeedingsimpleDataApartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REASite.Models.Addres", b =>
                {
                    b.Property<string>("HouseIndex")
                        .HasColumnType("text");

                    b.Property<string>("ApartmentID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HouseIndex");

                    b.ToTable("Addres");
                });

            modelBuilder.Entity("REASite.Models.ApartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("apartment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddresHouseIndex")
                        .HasColumnType("text");

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("RoomsCount")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imgURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isFavorite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AddresHouseIndex");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 0,
                            Description = "",
                            OfferType = "",
                            RoomsCount = (byte)0,
                            Title = "Apartment1",
                            imgURL = "",
                            isFavorite = false
                        },
                        new
                        {
                            Id = 2,
                            Area = 0,
                            Description = "",
                            OfferType = "",
                            RoomsCount = (byte)0,
                            Title = "Apartment2",
                            imgURL = "",
                            isFavorite = false
                        },
                        new
                        {
                            Id = 3,
                            Area = 0,
                            Description = "",
                            OfferType = "",
                            RoomsCount = (byte)0,
                            Title = "Apartment3",
                            imgURL = "",
                            isFavorite = false
                        },
                        new
                        {
                            Id = 4,
                            Area = 0,
                            Description = "",
                            OfferType = "",
                            RoomsCount = (byte)0,
                            Title = "Apartment4",
                            imgURL = "",
                            isFavorite = false
                        });
                });

            modelBuilder.Entity("REASite.Models.ApartmentModel", b =>
                {
                    b.HasOne("REASite.Models.Addres", "Addres")
                        .WithMany("Apartment")
                        .HasForeignKey("AddresHouseIndex");

                    b.Navigation("Addres");
                });

            modelBuilder.Entity("REASite.Models.Addres", b =>
                {
                    b.Navigation("Apartment");
                });
#pragma warning restore 612, 618
        }
    }
}
